# Generated by Django 2.2.4 on 2019-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaucu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='passport_issue_date',
            new_name='passport_issue',
        ),
        migrations.AlterField(
            model_name='flight',
            name='seat_class',
            field=models.CharField(choices=[('E', 'Economy'), ('D', 'Business'), ('F', 'First')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meal',
            field=models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('A', 'Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(choices=[('D', 'Double'), ('T', 'Triple'), ('Q', 'Quad'), ('S', 'Suite')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='view',
            field=models.CharField(choices=[('C', 'City'), ('H', 'Haram'), ('K', 'Kabah')], max_length=1),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='vehicle',
            field=models.CharField(choices=[('Saloon', 'Saloon'), ('GMC', 'GMC'), ('7 Seater', '7 seater'), ('10 Seater', '10 seater')], max_length=1),
        ),
    ]
